version: "3.3"
services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./static:/usr/src/app/static
    environment:
      DOMAIN: https://dndg.ru
      IMG_BASE_URL: 'https://thumb.cloud.mail.ru/weblink/thumb/xw20/'
      REDIS_URL: 'redis'

  worker:
    build:
      context: "."
      args:
        - "FLASK_ENV=${FLASK_ENV:-production}"
    command: celery worker -B -l info -A app.celery
    depends_on:
      - "redis"
    environment:
      DOMAIN: https://dndg.ru
      IMG_BASE_URL: 'https://thumb.cloud.mail.ru/weblink/thumb/xw20/'
      REDIS_URL: 'redis'
    restart: "${DOCKER_RESTART_POLICY:-unless-stopped}"
    stop_grace_period: "${DOCKER_STOP_GRACE_PERIOD:-3s}"
    volumes:
      - "${DOCKER_WEB_VOLUME:-./public:/app/public}"

  redis:
    image: "redis:alpine"

  nginx:
    image: nginx:1.17
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ~/certs:/certs
    depends_on:
      - web
  
